config/routes.rb
Rails.application.routes.draw do
  resources :pacientes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paciente.rb
class Paciente < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: %i[ show edit update destroy ]

  # GET /pacientes or /pacientes.json
  def index
    # TODO: #1 Nao deixar logs no codigo final
    Rails.logger.info params['nome']
    # TODO: #2 Despersonificar @pacientes, ajuda na heranca
    @pacientes = Paciente.all
    cpf = params['cpf'].delete('^0-9') unless params['cpf'].blank?
    rg = params['rg'].delete('^0-9') unless params['rg'].blank?
    # TODO: #3 Deixar a parte de busca mais dinamica, com um loop?
    # TODO: #4 Usar uma gem para cuidar da busca?
    @pacientes = @pacientes.where('nome LIKE ?', "%#{params['nome']}%") unless params['nome'].blank?
    @pacientes = @pacientes.where('cpf LIKE ?', "#{cpf}%") if cpf
    @pacientes = @pacientes.where('rg LIKE ?', "#{rg}%") if rg
    @pacientes = @pacientes.where('nome_mae LIKE ?', "#{params['nome_mae']}%") unless params['nome_mae'].blank?
    @pacientes = @pacientes.where('nome_pai LIKE ?', "#{params['nome_pai']}%") unless params['nome_pai'].blank?

    # TODO: #5 Usar uma gem para paginacao?
    page = params['page'].to_i
    @pacientes = @pacientes.limit(2)
    @pacientes = @pacientes.offset((page*2)-2) if page > 1

    sort_active = params['sort_active'] unless params['sort_active'].blank?
    sort_direction = params['sort_direction'] unless params['sort_direction'].blank?
    @pacientes = @pacientes.order("#{sort_active} #{sort_direction}") if (sort_active && sort_direction)
  end

  # GET /pacientes/1 or /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes or /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: "Paciente was successfully created." }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1 or /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: "Paciente was successfully updated." }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1 or /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: "Paciente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paciente_params
      params.require(:paciente).permit(:nome, :data_nascimento, :rg, :cpf, :sexo, :cor, :nome_mae, :nome_pai, :cep, :localidade, :uf, :ibge, :logradouro, :complemento, :bairro, :numero, :convenio, :titular_conv, :carteirinha_conv, :validade_conv, :cns_conv, :receber_infadc, :receber_email, :receber_sms, :observacao, :telefone, :email, :celular)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente) do |form| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
        <% paciente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.date_select :data_nascimento %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.text_field :rg %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo %>
  </div>

  <div class="field">
    <%= form.label :cor %>
    <%= form.text_field :cor %>
  </div>

  <div class="field">
    <%= form.label :nome_mae %>
    <%= form.text_field :nome_mae %>
  </div>

  <div class="field">
    <%= form.label :nome_pai %>
    <%= form.text_field :nome_pai %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.number_field :cep %>
  </div>

  <div class="field">
    <%= form.label :localidade %>
    <%= form.text_field :localidade %>
  </div>

  <div class="field">
    <%= form.label :uf %>
    <%= form.text_field :uf %>
  </div>

  <div class="field">
    <%= form.label :ibge %>
    <%= form.number_field :ibge %>
  </div>

  <div class="field">
    <%= form.label :logradouro %>
    <%= form.text_field :logradouro %>
  </div>

  <div class="field">
    <%= form.label :complemento %>
    <%= form.text_field :complemento %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero %>
  </div>

  <div class="field">
    <%= form.label :convenio %>
    <%= form.text_field :convenio %>
  </div>

  <div class="field">
    <%= form.label :titular_conv %>
    <%= form.text_field :titular_conv %>
  </div>

  <div class="field">
    <%= form.label :carteirinha_conv %>
    <%= form.text_field :carteirinha_conv %>
  </div>

  <div class="field">
    <%= form.label :validade_conv %>
    <%= form.date_select :validade_conv %>
  </div>

  <div class="field">
    <%= form.label :cns_conv %>
    <%= form.text_field :cns_conv %>
  </div>

  <div class="field">
    <%= form.label :receber_infadc %>
    <%= form.check_box :receber_infadc %>
  </div>

  <div class="field">
    <%= form.label :receber_email %>
    <%= form.check_box :receber_email %>
  </div>

  <div class="field">
    <%= form.label :receber_sms %>
    <%= form.check_box :receber_sms %>
  </div>

  <div class="field">
    <%= form.label :observacao %>
    <%= form.text_area :observacao %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<h1>Editing Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data nascimento</th>
      <th>Rg</th>
      <th>Cpf</th>
      <th>Sexo</th>
      <th>Cor</th>
      <th>Nome mae</th>
      <th>Nome pai</th>
      <th>Cep</th>
      <th>Localidade</th>
      <th>Uf</th>
      <th>Ibge</th>
      <th>Logradouro</th>
      <th>Complemento</th>
      <th>Bairro</th>
      <th>Numero</th>
      <th>Convenio</th>
      <th>Titular conv</th>
      <th>Carteirinha conv</th>
      <th>Validade conv</th>
      <th>Cns conv</th>
      <th>Receber infadc</th>
      <th>Receber email</th>
      <th>Receber sms</th>
      <th>Observacao</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nome %></td>
        <td><%= paciente.data_nascimento %></td>
        <td><%= paciente.rg %></td>
        <td><%= paciente.cpf %></td>
        <td><%= paciente.sexo %></td>
        <td><%= paciente.cor %></td>
        <td><%= paciente.nome_mae %></td>
        <td><%= paciente.nome_pai %></td>
        <td><%= paciente.cep %></td>
        <td><%= paciente.localidade %></td>
        <td><%= paciente.uf %></td>
        <td><%= paciente.ibge %></td>
        <td><%= paciente.logradouro %></td>
        <td><%= paciente.complemento %></td>
        <td><%= paciente.bairro %></td>
        <td><%= paciente.numero %></td>
        <td><%= paciente.convenio %></td>
        <td><%= paciente.titular_conv %></td>
        <td><%= paciente.carteirinha_conv %></td>
        <td><%= paciente.validade_conv %></td>
        <td><%= paciente.cns_conv %></td>
        <td><%= paciente.receber_infadc %></td>
        <td><%= paciente.receber_email %></td>
        <td><%= paciente.receber_sms %></td>
        <td><%= paciente.observacao %></td>
        <td><%= paciente.telefone %></td>
        <td><%= paciente.email %></td>
        <td><%= paciente.celular %></td>
        <td><%= link_to 'Show', paciente %></td>
        <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destroy', paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paciente', new_paciente_path %>

app/views/pacientes/new.html.erb
<h1>New Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Back', pacientes_path %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @paciente.nome %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @paciente.data_nascimento %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @paciente.rg %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @paciente.cpf %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @paciente.sexo %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @paciente.cor %>
</p>

<p>
  <strong>Nome mae:</strong>
  <%= @paciente.nome_mae %>
</p>

<p>
  <strong>Nome pai:</strong>
  <%= @paciente.nome_pai %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @paciente.cep %>
</p>

<p>
  <strong>Localidade:</strong>
  <%= @paciente.localidade %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @paciente.uf %>
</p>

<p>
  <strong>Ibge:</strong>
  <%= @paciente.ibge %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @paciente.logradouro %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @paciente.complemento %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @paciente.bairro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @paciente.numero %>
</p>

<p>
  <strong>Convenio:</strong>
  <%= @paciente.convenio %>
</p>

<p>
  <strong>Titular conv:</strong>
  <%= @paciente.titular_conv %>
</p>

<p>
  <strong>Carteirinha conv:</strong>
  <%= @paciente.carteirinha_conv %>
</p>

<p>
  <strong>Validade conv:</strong>
  <%= @paciente.validade_conv %>
</p>

<p>
  <strong>Cns conv:</strong>
  <%= @paciente.cns_conv %>
</p>

<p>
  <strong>Receber infadc:</strong>
  <%= @paciente.receber_infadc %>
</p>

<p>
  <strong>Receber email:</strong>
  <%= @paciente.receber_email %>
</p>

<p>
  <strong>Receber sms:</strong>
  <%= @paciente.receber_sms %>
</p>

<p>
  <strong>Observacao:</strong>
  <%= @paciente.observacao %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @paciente.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @paciente.email %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @paciente.celular %>
</p>

<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>